---
- name: Verify
  hosts: all
  become: false
  gather_facts: false

  vars_files:
    - ../../defaults/main.yml

  tasks:
    - name: Check the hugo version.
      shell: "{{ hugo_bin_path }} version | grep -oP 'v[^-]+'"
      changed_when: false
      register: hugo_verify_version

    - name: Verify hugo's version is {{ hugo_version }}
      assert:
        that:
          - hugo_version in hugo_verify_version.stdout
